### ISSUE TITLE
Weight international inter-state pegs differently

### ISSUE THREAD

**Issue by Lauraducky** [GlobalX/pockybot#128]
PockyBot should encourage collaboration between teams in different locations. A solution to this would be to give extra weight to pegs given to people in a location remote to the sender.

Proposed solution: add an extra table in the database to record which location a sender is based at. Add a new "location" command to update these on the fly. This command should allow the user to add multiple people at once. Then, add into the config (number config?) a multiplier for pegs between two locations (perhaps with the format: multiplier-location1-location2). Finally, each user should have their location listed in the final results, and inter-location pegs should be listed as such (along with accompanying multiplier?)

Nice-to-have: an additional command which lists out the users who have not been assigned a location.

**Comment by Lauraducky** [comment]
Also might be needed: A command to wipe a user from the db (for people who have left)

**Comment by jimcullenaus** [comment]
Huh. Did we not already have a story for this?

**Comment by gillianmilne** [comment]
hmm, how "completely optional" can we make this? Given open source and other potential users

**Comment by jimcullenaus** [comment]
Well we could set a default location if none is specified, and any hypothetical other users could simply not put anyone in a separate location if they don't want to.
