### ISSUE TITLE
Finish response should not include the winners

### ISSUE THREAD

**Issue by jimcullenaus** [GlobalX/pockybot#152]
## Is your feature request related to a problem? Please describe.

When calling `finish`, PockyBot responds with a formatted table of the winners and the pegs they have received, as well as a link to a web page containing all of the winners and the full results.

## Describe the solution you'd like

The response should only include the link to full results, and not include the preview of the winners.

**Comment by gillianmilne** [comment]
should the functionality be removed, or configurable?

**Comment by jimcullenaus** [comment]
I would say remove, because the information is duplicated from the linked version. But would value others' input.

**Comment by gillianmilne** [comment]
I was thinking say, other people who may use this may want one, or the other or both even.
