### ISSUE TITLE
Results categories

### ISSUE THREAD

**Issue by arthurs** [GlobalX/pockybot#22]
There should be a way to view what category each person was given a peg for, so you could potentially separate winners for each category. this could either be in the main results views we currently have, or run as a separate view.

**Comment by Evangelinexx** [comment]
Thoughts on this mockup? Just as a starting point. I think we need more design work to figure out how category winners would work.

![image](https://user-images.githubusercontent.com/14936730/52822005-404a1700-30fc-11e9-90b0-c78eaa59d371.png)

**Comment by Lauraducky** [comment]
Yeah I like that as a start. Perhaps there's a way we could differentiate them even more (colour coding the keywords?) Just a thought

**Comment by Lauraducky** [comment]
I think we should separate out the two views (regular results vs category view) if we have a more specific categories view but I also like the idea of keeping it as one page (perhaps we could do a [dynamic tabs](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_js_tab&stacked=h) thing for people with JS enabled. Would also need to think about how it would look on mobile ofc

**Comment by arthurs** [comment]
could we maybe do something like just have a count for each person? so at the end of the fornight we can just look at how many of each type you got. its main purpose was so that David could push them to employee of the month, possible combine it with Evelyn's concept above i think it would provide all the information we need

**Comment by Evangelinexx** [comment]
@arthurs Perhaps we keep the category winners in a separate service which can be called via a categories trigger
```@PockyBot categories```
Which would mean David could call that whenever he needs to find out what the category results are.
We would most likely want that to generate a html doc if that's easiest/nicest to show the category results.

Then the finish trigger could call the categories service as well to generate and include the categories html in the response.

**Comment by arthurs** [comment]
i think that would work, so long as we ran it on finish as well cause the tables get wiped

**Comment by Evangelinexx** [comment]
As I said:
> Then the finish trigger could call the categories service as well to generate and include the categories html in the response.
