### ISSUE TITLE
No continuous integration or automated testing

### ISSUE THREAD

**Issue by jimcullenaus** [GlobalX/pockybot#37]
Should hook up the bot's GitHub to connect to some sort of automated testing framework.

**Comment by Lauraducky** [comment]
Here's an option: [Travis CI](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup) is free for open source projects.

**Comment by jimcullenaus** [comment]
I think Travis CI is what I used for my name-sorter. It worked pretty well. Dunno.
