### ISSUE TITLE
Add winners to html results view

### ISSUE THREAD

**Issue by arthurs** [GlobalX/pockybot#45]
So that we don't confuse people who havn't given out enough pegs as winners (they are really just losers) we should have a winner category at the top of the page

**Comment by Evangelinexx** [comment]
To make it all in one place and avoid duplication, propose the following within the file:
- Winners
- Other pegs (without winners) from most to least pegs

**Comment by jimcullenaus** [comment]
If the winners are going to be placed in the same file as the results, this might also be a good opportunity to complete #42 simultaneously.

**Comment by Evangelinexx** [comment]
@jimcullenaus so with #42, are we looking to have finish instead call:
- results (to create the results file and share it)
- notify (or whatever we want to call it, to PM the resuls)
- reset (reset the DB)

**Comment by jimcullenaus** [comment]
We'd have a winners service and a results service, which pull out the arrays of winners and results, respectively. Then the winners and results triggers would call these services and format the response in a way appropriate for the purposes of just displaying the results/winners.

The finish trigger would call *both* of these services and then format it appropriately (the HTML you're talking about) as well as PMing everyone's results.

**Comment by jimcullenaus** [comment]
At least, that's my thought on it. Open to other ideas.

**Comment by Lauraducky** [comment]
I always thought it was a little ghetto having triggers call other triggers so +1 to separating it out
