### ISSUE TITLE
Unpeg abstract concepts

### ISSUE THREAD

**Issue by Evangelinexx** [GlobalX/pockybot#55]
If no PM is present:
``` @Pockybot unpeg Webex for reasons ```

Pockybot uses the first word after the unpeg as the person to unpeg.

Open to discussion if there are better ideas, as this will not allow unpegging abstract concepts that are more than one word long.

**Comment by jimcullenaus** [comment]
Some alternatives:

* PockyBot uses all words up until the first "for" or "because" as the person to unpeg.
* Message must be in the format `@PockyBot unpeg *an abstract concept* for reasons`

**Comment by Evangelinexx** [comment]
How about it uses all words up until the first 'for', or just the first one if there is no 'for'?

**Comment by jimcullenaus** [comment]
Yeah that could work.
