### ISSUE TITLE
Stop PockyBot from messaging other bots

### ISSUE THREAD

**Issue by Lauraducky** [GlobalX/pockybot#67]
If you use PockyBot to message another bot it will PM it. If the other bot messages back it will result in an infinite loop of bots messaging one another. Before PockyBot sends a PM it should check whether the user is a bot and not send a message if the user is a bot

**Comment by jimcullenaus** [comment]
[Related API doc for reference] (https://developer.webex.com/docs/api/v1/people/get-person-details)
