### ISSUE TITLE
Introduce penalty keywords

### ISSUE THREAD

**Issue by jimcullenaus** [GlobalX/pockybot#91]
**Is your feature request related to a problem? Please describe.**

Users who get shamed repeatedly lose the ability to reward others. This penalises others more than the shamed person. It also means that if they have given out their limit in legitimate pegs, they cannot be shamed any further.

**Describe the solution you'd like**

Introduce a separate class of penalty keywords. Pegs with these keywords would not count against the fortnightly peg limit, but would count at a penalty (defined in the database) in totalling the number of pegs received at the end of the fortnight.

**Describe alternatives you've considered**

* Don't penalise, but still have a class of keywords that would not count against the limit.
* Have a class of keywords where a single instance results in instant disqualification from winning.

**Additional context**

In our implementation, the only penalty keyword currently would be 'shame'. Should be flexible enough to allow multiple different options, and to work with #21 when/if that is implemented.

**Comment by Lauraducky** [comment]
Still need to remove penalty pegs from the list of general results and add it to its own results tab

**Comment by jimcullenaus** [comment]
Do you wanna do that part of it and I'll work on the actual penalty part?

**Comment by Lauraducky** [comment]
Sure, that works. Should be able to do that without stepping on each other's toes
